### ISSUE TITLE
API Desing

### ISSUE THREAD

**Issue by aberba** [gecko0307/dagon#1]
Please take a look at babylonJS game framework for inspiration on API namings and design

**Comment by gecko0307** [comment]
I'm not getting the point of this proposal. Do you mean making API as close to an existing engine as possible for easy migration? That's not the goal of this project. More conforming class names? Please point out where exactly Dagon's class names don't correspond to their functionality. I believe all of them are properly named.
I've never used BabylonJS, but, according to samples, they seem to use a namespace (e.g., `BABYLON.Mesh.CreateSphere`). I'm not a fan of this approach. Smaller code, better code. And needless to say that in D explicit namespaces are obsolete because you can always do a named import if you wish (`import Dagon = dagon;`) and use `Dagon.` as a prefix for everything.
OK, as the most of JS libs, Babylon is asynchronous and uses closures, and Dagon doesn't. Again, making asynchronous engine was not my goal, and this was not only an API design question, but an architectural decision. Dagon is a simple object-oriented framework where you inherit and extend built-in classes, overriding event handlers, etc. I understand that not everyone likes doing things this way, but this is just a matter of personal preferences.

**Comment by aberba** [comment]
Not the e modules but the usage. Babylon feels like pluggable components.
Attaching things to things. Feel natural. Was a suggestion
