### ISSUE TITLE
Releases on Dub repository

### ISSUE THREAD

**Issue by aberba** [gecko0307/dagon#25]
Hello Gecko, I'm not seeing Dagon releases appear on the Dub repository. Why is this so?

**Comment by gecko0307** [comment]
Releases take some time to appear in registry, because they're queued. 0.8.2 is visible now, and I've successfully built a test project with it. Keep in mind though that this is just a compatibility fix version that I've branched from 0.8.0, it doesn't add any features. All new stuff including deferred rendering is in master, which is not released yet.
