### ISSUE TITLE
Need more details in documentation.

### ISSUE THREAD

**Issue by aferust** [gecko0307/dagon#42]
This engine attracts my attention, since I love playing around game engines as an amateur programmer and newbie for dlang. The first thing I realized is that the documentation do not cover many things. I digged into the source code a bit, and there are things I could not find out:

1) Is there an approach like nodes in Ogre3d? You can have nested nodes behaving like hinges with Ogre3D. Or is it only posible to append Entities to a scene? Edit: I think the answer is in Entity class which may have children recursively: DynamicArray!Entity children; ?

2) How to remove/deallocate an Entity after createEntity3D(). Edit: The way I found out is calling this.entities3D.removeKey(entity.id); entity.release(); in derived Scene class?

3) Is there any built-in functionality to permit objects emitting stereo sound (something like an OpenAL integration)

4) Is there any implementation similar to actions in cocos2dx (https://docs.cocos2d-x.org/cocos2d-x/en/actions/) or LibGdx (https://github.com/libgdx/libgdx/wiki/Scene2d#actions). I see a class member named "behaviours"?

**Comment by denizzzka** [comment]
5. Where is from .asset files? How to create my own .asset file?

**Comment by gecko0307** [comment]
1. It is possible to create an entity as a child of another entity by calling `createEntity3D(parent)`.
2. Explicit object removing on user side is not yet implemented properly. All entities are released automatically when the scene is released. I'm planning to add this feature. Nevertheless, calling `removeKey` should work in the sense of removing an entity from the rendering list, but it will still leave a dangling pointer in ownership mechanism, so the object can't be destroyed safely (will cause double free error).
3. There's no sound support. I doubt that I'll integrate a sound library any time soon because there is no obvious candidate. Using a low-level library like OpenAL would mean implementing sound files decoding also. I have a working wav loader in dlib, but I'm currently don't have much time/will to write Vorbis or MP3 decoder. I cound integrate a good high-level sound library with C API (or at least a multi-format decoder) but I've yet to see one.
4. No, behaviours are different, they are part of entity/component paradigm. But animation actions are an interesting feature, I'll consider implementing something like them.

**Comment by aferust** [comment]
Thanks for clarifications. I think explicit object removing should be a priority to implement. As an example usage case: my spaceship is launching some crazy missiles. I want them dealocate when they reach a distance or hit the target. I know that entities can be reused for such situation. Still it would be nice to get rid of them safely. Cocos2dx has a reference counting mechanism for that. I am not sure if it is possible to implement such thing in D. As I said I am newbie to many things here.
