### ISSUE TITLE
Glyph ranges detection

### ISSUE THREAD

**Issue by Timu5** [gecko0307/dagon#47]
What do you thinks about glyph ranges detection for text rendering in GUI. Personally I see four options for that matter:

1. Static glyph ranges, either hard coded in code(current approach) or loaded from configuration.
2. Based on system locale(it might be hard to find table that translate locale code into UTF ranges).
3. Dynamic, loading glyph range when new character occurs in string.
4. Utilize ftfont(and its character loading) for rendering instead of nuklear builtin font renderer.

**Comment by gecko0307** [comment]
I think we shouldn't hardcode ranges. The user should be allowed to set up them how he wants. This is very game specific, because if the game is English-only, one doesn't need any Unicode at all. Still the game may allow the player to type Unicode characters (e.g. when prompting for a name), but then again the engine shouldn't decide for user what languages he should support in his game. System locale should be available for the user to base his decision on.
4 seems the most nice solution for me, though I don't know Nuklear enough to say whether it is possible.

**Comment by Timu5** [comment]
It's definitely possible to integrate them. There are two approaches:
1. Use ftfont as is, but requires to implement all primitives drawing on our own.
2. Modify ftfont to use one atlas texture per font, instead of one per glyph, and still use nuklear primitives drawing routines.
