### ISSUE TITLE
Vulkan support

### ISSUE THREAD

**Issue by Duel05** [gecko0307/dagon#68]
It would be really cool if Vulkan was supported in dagon. This would allow dagon to run on Apple devices, and there are active bindings for Vulkan ([ErupteD](https://github.com/ParticlePeter/ErupteD)).
This would be way later down the line because of the amount of work that would have to be put in, but I think it is essential to implement support for Vulkan.

**Comment by gecko0307** [comment]
It is possible that the engine will be ported to [wgpu](https://github.com/gfx-rs/wgpu-native) some day in the future, or to similar API. I'm against using Vulkan directly, there should be an intermediate layer with multiple backends.

**Comment by DuelTheBearded** [comment]
> It is possible that the engine will be ported to [wgpu](https://github.com/gfx-rs/wgpu-native) some day in the future, or to similar API. I'm against using Vulkan directly, there should be an intermediate layer with multiple backends.

Why are you against using Vulkan directly? Just curious.

**Comment by gecko0307** [comment]
Doing that will tightly bind the engine's logic to Vulkan's structures and execution models in their current state of affair, which is a bad thing in the long run, because the API is new and will most likely change. Due to the specificity of Vulkan's architecture, it can't be easily "added" to an existing single-API engine like Dagon (OpenGL functionality doesn't map one-to-one to Vulkan, the engine should be heavily adapted and rewritten in many places). So before adopting Vulkan, Dagon should be decoupled from OpenGL first, there should be some mid-level graphics library with system-specific code at the backend. I had a plan to write it in the past, but currently I don't think that's practical anymore because there is wgpu, and it is exactly what I need.

**Comment by DuelTheBearded** [comment]
Yeah, that makes sense.

**Comment by aviallon** [comment]
Why not using gfx rs instead ?
I think it is more mature than wgpu.

**Comment by gecko0307** [comment]
Does it have C interface? I thought it's native Rust library. wgpu's internals, AFAIK, have been forked from gfx-hal, so I think they are close in terms of stability (I didn't really compare them, though). 
Of course it would be nice to have a choise, but wgpu currently seems like the only cross-language option.

**Comment by aviallon** [comment]
https://github.com/gfx-rs/portability

**Comment by aviallon** [comment]
And wgpu is actually built on top of gfx-rs, which is lower level.

**Comment by gecko0307** [comment]
Closing the issue due to the fact that, if such a port will ever happen, I won't use Vulkan directly anyway.
